#!/usr/bin/env bash

options=(
	style=round
	width=6.0
	hidpi=off
	active_color="gradient(top_right=0xffa6e3a1,bottom_left=0xfff38ba8)"
	inactive_color="gradient(top_right=0xff89b4fa,bottom_left=0xffcba6f7)"
)

borders "${options[@]}"
