conky.config = {
	alignment = "bottom_right",
	background = true,
	border_width = 1,
	cpu_avg_samples = 2,
	default_color = "70c0b1",
	color2 = "eaeaea",
	default_outline_color = "white",
	default_shade_color = "white",
	double_buffer = true,
	draw_borders = false,
	draw_graph_borders = true,
	draw_outline = false,
	draw_shades = false,
	extra_newline = false,
	font = "JetBrainsMono Nerd Font:size=12",
	font0 = "JetBrainsMono Nerd Font:size=12",
	font1 = "JetBrainsMono Nerd Font:size=10",
	font2 = "JetBrainsMono Nerd Font:size=12:bold",
	font3 = "JetBrainsMono Nerd Font:size=10:bold",
	gap_x = 60,
	gap_y = 60,
	minimum_height = 5,
	minimum_width = 5,
	net_avg_samples = 2,
	no_buffers = true,
	out_to_console = false,
	out_to_ncurses = false,
	out_to_stderr = false,
	-- out_to_wayland = false, -- for X11
	out_to_wayland = true, -- for wayland
	-- out_to_x = true, -- for X11
  out_to_x = false, -- for wayland
	own_window = true,
	own_window_class = "Conky",
	own_window_type = "override",
	own_window_hints = "undecorated,sticky,below,skip_taskbar,skip_pager",
	show_graph_range = false,
	show_graph_scale = false,
	stippled_borders = 0,
	update_interval = 1.0,
	uppercase = false,
	use_spacer = "none",
	use_xft = true,
}

conky.text = [[
${voffset 8}$color2${font JetBrainsMono Nerd Font:size=16}${time %A}$font\
${voffset -8}$alignr$color${font JetBrainsMono Nerd Font:size=38}${time %e}$font
$color${voffset -30}$color${font JetBrainsMono Nerd Font:size=18}${time %b}$font\
${voffset -3} $color${font JetBrainsMono Nerd Font:size=20}${time %Y}$font$color2$hr
#
${voffset 20}${goto 10}${color}${font0}NETWORK
${if_existing /proc/net/route wlp58s0} ${font JetBrainsMono Nerd Font:italic:size=12} $alignc Wireless
${goto 10}${color2}${font1}Connection quality $alignr ${color}${wireless_link_qual_perc wlp58s0}%
${goto 10}${color2}${font1}Down ${color}${downspeed wlp58s0} kb/s $alignr ${color2}Total: ${color}${totaldown wlp58s0}
${goto 10}${color2}${font1}Up   ${color}${upspeed wlp58s0} kb/s $alignr ${color2}Total: ${color}${totalup wlp58s0}
${endif}
#
${voffset 10}${goto 10}${color}${font0}CPU$alignr${font0}$cpu%
${voffset 5}${goto 10}${font}${color2}${top name 1}$alignr$color${top cpu 1}%
${goto 10}${color2}${top name 2}$alignr$color${top cpu 2}%
${goto 10}${color2}${top name 3}$alignr$color${top cpu 3}%
${goto 10}${color2}${top name 4}$alignr$color${top cpu 4}%
${goto 10}${color2}${top name 5}$alignr$color${top cpu 5}%
#
${voffset 10}${goto 10}${color}${font0}RAM$alignr${font0}$mem$font
${voffset 5}${goto 10}$color2${top_mem name 1}$alignr${color}${top_mem mem_res 1}
${goto 10}${color2}${top_mem name 2}$alignr${color}${top_mem mem_res 2}
${goto 10}${color2}${top_mem name 3}$alignr${color}${top_mem mem_res 3}
${goto 10}${color2}${top_mem name 4}$alignr${color}${top_mem mem_res 4}
${goto 10}${color2}${top_mem name 5}$alignr${color}${top_mem mem_res 5}
#
${voffset 10}${goto 10}${color}${font0}Root$alignr${font0}${fs_used}/ ${fs_size}
${voffset 10}${color2}${alignr}${execi 1200 whoami}@${nodename}
${alignr}${color2}${font1}uptime: ${color}${uptime_short}
${voffset 5}${color2}${font1}${alignr}kernel: ${color}${kernel}
]]
